### ISSUE TITLE
Suggestion :)

### ISSUE THREAD

**Issue by Shinoyx** [teralove/translate-chat#4]
Hi Teralove!

Was testing around with it and this mod is amazing for me cause I play KTERA and I can't read Korean.
So here are two suggestions ~

1) Had a friend to pm me some Korean text but when I wanna reply him by using /r, it was send to <his name>(translated) instead. For whispers, remove that (translated) so that /r will work.

2) Can we have choice for translating which kind of text. Ex. I only want guild, party text to be translated and not global, trade chats. Maybe like a config.json or command settings to enable and disable which kind of messages to be translated. 

Really thank you for all your mods they are all super helpful! :)

**Comment by teralove** [comment]
1. Your sent messages are being translated? That's unintended,
2. Shouldn't be difficult, just need a list of channels to include.

**Comment by Shinoyx** [comment]
Nooo, the sent messages isn't translated. What I mean for point 1 is when I did /r to reply to pms, it was replying message to (his name) (translated). Which that character did not exist. 

Example. MynameisA whispered me and the message was translated. I wanna reply him so I did a /r <space> and it automatically set to reply to MynameisA (translated) which that character doesn't exist.

**Comment by teralove** [comment]
ok
